version: '3.7'

services:

  deloreans-build:
    build:
      context: .
      target: dev
    image: deloreans:${IMAGE_TAG:-latest}

  deloreans-run:
    image: deloreans:${IMAGE_TAG:-latest}
    volumes:
      - ./:/app/deloreans/
    command: ["tail", "-f", "/dev/null"]

  deloreans-test:
    image: deloreans:${IMAGE_TAG:-latest}
    volumes:
      - ./coverage_report:/app/deloreans/coverage_report
    command: make test

  deloreans-lint:
    image: deloreans:${IMAGE_TAG:-latest}
    command: make lint

  deloreans-type-hint:
    image: deloreans:${IMAGE_TAG:-latest}
    command: make type-hint
