version: '3.7'

services:

  delorean-build:
    build:
      context: .
      target: dev
    image: delorean:${IMAGE_TAG:-latest}

  delorean-run:
    image: delorean:${IMAGE_TAG:-latest}
    volumes:
      - ./:/app/delorean/
    command: ["tail", "-f", "/dev/null"]

  delorean-test:
    image: delorean:${IMAGE_TAG:-latest}
    volumes:
      - ./coverage_report:/app/delorean/coverage_report
    command: make test

  delorean-lint:
    image: delorean:${IMAGE_TAG:-latest}
    command: make lint

  delorean-type-hint:
    image: delorean:${IMAGE_TAG:-latest}
    command: make type-hint
