name: Publish Python Package

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Dependencies
        env:
          POETRY_VERSION: 1.4.2
          POETRY_NO_INTERACTION: 1
          POETRY_VIRTUALENVS_CREATE: false
        run: |
          pip install poetry
          poetry install

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build --username __token__ --password $POETRY_PYPI_TOKEN_PYPI
