name: Coverage

on:
  push:
    branches: [main, 'release*']

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.7
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Install Dependencies
        env:
          POETRY_VERSION: 1.4.2
          POETRY_NO_INTERACTION: 1
          POETRY_VIRTUALENVS_CREATE: false
        run: |
          pip install poetry
          poetry install

      - name: Run unittest cases
        run: make test

      - name: Test coverage comment
        uses: MishaKav/pytest-coverage-comment@v1.1.50
        id: coverageComment
        with:
          junitxml-path: coverage_report/pytest.xml
          pytest-xml-coverage-path: coverage_report/cov.xml

      - name: Create the Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 2c9c2c824a9b4150718e84579abbe456
          filename: badge.json
          label: coverage
          message: ${{ steps.coverageComment.outputs.coverage }}
          color: ${{ steps.coverageComment.outputs.color }}
          namedLogo: python
